package uz.texnomart.enums;

public enum AdminStatus {
    SHOW_USERS,
    SEND_ADS,
    SHOW_MESSAGES,
    PRODUCTS,
    DISCOUNT,
    ADD_DISCOUNT,
    DELETE_DISCOUNT,
    SEND_DISCOUNT_PERCENTAGE,
    SEND_DISCOUNT_START_END_TIME,
    DISCOUNT_CONFIRM,
    CATEGORIES,
    ORDER_LIST,
    ADMIN_CRUD,
    ADD_ADMIN,
    REMOVE_ADMIN
}
