package uz.texnomart.enums;

public enum AdminStatus {
    SHOW_USERS,
    SEND_ADS,
    EDIT_ADMIN,
    SHOW_MESSAGES,
    PRODUCTS,
    ADD_DISCOUNT,
    SEND_DISCOUNT_PERCENTAGE,
    SEND_DISCOUNT_START_END_TIME,
    DISCOUNT_CONFIRM,
    CATEGORIES,
    ORDER_LIST,
}
